import time
import os

print("Disclaimer: NOT A GAME..")
time.sleep(2)
os.system("clear")
a = input("Ready for some Noot noot [y] or [n]?\n")
if a == 'y':
  os.system("clear")
  print("noot noot incoming.....")
  time.sleep(2)
  os.system("clear")
  print("NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT TOON NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT ")
  b1 = input("Did you find any other word than NOOT [y] or [n]?\n")
  if b1 == "y":
    c1 = input("What was it?\n")
    if c1 == "TOON":
      print("meh you won. sheesh")
    else:
      print("oof, I won.")
      time.sleep(2)
      os.system("clear")
      time.sleep(2)
      print("GAME ENDED BRO.")
      
  elif b1 == "n":
    print("Ohk. I won anyways...")
    time.sleep(2)
    os.system("clear")
    time.sleep(2)
    print("GAME ENDED BRO.")

  
elif a == "n":
  os.system("clear")
  print("I dont't care hehe....")
  time.sleep(2)
  print("NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT TOON NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT NOOT")
  b = input("Did you find any other word than NOOT [y] or [n]?\n")
  if b == "y":
    c = input("What was it?\n")
    if c == "TOON":
      print("meh you won. sheesh")
    else:
      print("oof, I won.")
      time.sleep(2)
      os.system("clear")
      time.sleep(2)
      print("GAME ENDED BRO.")
  elif b == "n":
    print("Ohk. I won anyways...")
    time.sleep(2)
    os.system("clear")
    time.sleep(2)
    print("GAME ENDED BRO.")
